  private Operation<PromiseError> onFailure(final CompleteCallback callback) {
    return error -> callback.onFailure(error.getCause());
  }

