  @Test
  public void shouldNotifyOnFailedRevert() throws Exception {
    RevertResult revertResult = mock(RevertResult.class);
    when(revertResult.getNewHead()).thenReturn("1234");
    when(revertResult.getRevertedCommits()).thenReturn(Collections.emptyList());
    when(revertResult.getConflicts()).thenReturn(Collections.emptyMap());

    Revision selectedRevision = mock(Revision.class);
    when(selectedRevision.getId()).thenReturn("1234");

    presenter.show(project);
    presenter.onRevisionSelected(selectedRevision);
    presenter.onRevertClicked();
    verify(revertPromise).catchError(promiseErrorCaptor.capture());
    promiseErrorCaptor.getValue().apply(mock(PromiseError.class));

    verify(notificationManager).notify(eq(constant.revertCommitFailed()), eq(FAIL), eq(FLOAT_MODE));
  }

