    @Test(expectedExceptions = java.io.IOException.class, expectedExceptionsMessageRegExp = "Docker image build failed")
    public void shouldThrowIOExceptionWhenBuildImageButNoSuccessMessageInResponse() throws IOException, InterruptedException {
        AuthConfigs authConfigs = DtoFactory.newDto(AuthConfigs.class);
        AuthConfig authConfig = DtoFactory.newDto(AuthConfig.class);
        Map<String, AuthConfig> auth = new HashMap<>();
        auth.put("auth", authConfig);
        authConfigs.setConfigs(auth);

        BuildImageParams getEventsParams = BuildImageParams.create(dockerfile)
                                                           .withAuthConfigs(authConfigs);

        doReturn(new ByteArrayInputStream("c96d378b4911: Already exists".getBytes())).when(dockerResponse).getInputStream();

        dockerConnector.buildImage(getEventsParams, progressMonitor);

        verify(dockerResponse).getInputStream();
    }

